### ISSUE TITLE
bson.deserialize Invalid UTF8 string

### ISSUE THREAD

**Issue by rasco** [mongodb-js/bson-ext#60]
Ok so I'm not actually 100% sure the bug is in bson-ext or the node MongoDB driver – but as soon as I disable bson-ext, this error doesn't occur anymore:

(this error happens while the node mongo driver uses deserialize with bson-ext)
```
Error: Invalid UTF8 string found                                                                                  
    at BinMsg.parse (/usr/src/app/node_modules/mongodb/lib/core/connection/msg.js:203:51)                         
    at Connection.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:424:17)              
    at Connection.emit (events.js:203:13)                                                                         
    at processMessage (/usr/src/app/node_modules/mongodb/lib/core/connection/connection.js:384:10)                
    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connection.js:553:15)            
    at Socket.emit (events.js:203:13)                                                                             
    at addChunk (_stream_readable.js:294:12)                                                                      
    at readableAddChunk (_stream_readable.js:275:11)                                                              
    at Socket.Readable.push (_stream_readable.js:210:10)                                                          
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {                                                
  name: 'MongoError'
}
```

The bson.deserialize function fails and it seems that it throws that exception:
``ThrowAllocatedStringException(64, "Invalid UTF8 string found");``

I'm wondering why this doesn't happen when bson-ext is disabled.
Is there actually a bug in bson-ext?
Or does the node mongodb driver's own BSON do some additional error checking or sanity checking which prevents this error?

Unfortunately I can't provide any sample data.

**Comment by valeriansaliou** [comment]
Hello. We have been using `bson-ext` in production at Crisp over a period of 1 month, and we've seen such errors as well.

I've got hold on an UTF-8 string which triggered that deserialization error, which is (note that it's an user-generated message, hence the garbage):

```
**Zal👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍**
```

Our systems cut out long texts for preview purposes, for which I guess a 👍 smiley character got cut in half, so this became (as reported by Mongo Shell):

```
*Zal👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍���[..]
```

Which `bson-ext` would **NOT** be willing to deserialize (it throws `Invalid UTF8 string found`). Note the addition of `[..]` which is done by our systems.

_Note that Mongoose's JS BSON library would not throw when deserializing the same string (?!)._

I've tried using Mongoose's JS BSON library instead of `bson-ext`, for insertion only. In that case, this gave the inserted value (as reported by Mongo Shell):

```
*Zal👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍�[..]
```

Which `bson-ext` would happily deserialize.

**Judging from that, `bson-ext` serializer is producing invalid UTF-8 strings in some cases where UTF-8 characters were split.**

**Comment by nbbeeken** [comment]
Hello, thanks for bringing our attention to this, it has sparked a larger conversation about how BSON libraries should handle UTF-8 issues across drivers. Currently if you use the code there:
```js
// '👍' is UTF-16 D83D DC4D
'👍'.substr(0, 1) // === '�' or D83D
```
The result is the first sequence of a UTF-16 surrogate pair D83D which is not a valid character so there is no way to represent it in UTF8. The reason that `js-bson` handles this seemingly without error is because it is using nodejs' Buffer under the hood. [Buffer](https://nodejs.org/dist/latest-v14.x/docs/api/buffer.html#buffer_buffers_and_character_encodings), when serializing a JS string, if it encounters a sequence that cannot be encoded it will fill in [U+FFFD the replacement character](https://simonsapin.github.io/wtf-8/). This allows most of the string to be round tripped even though it lost information in the process. `bson-ext` does not use these same nodejs APIs and so does not follow this same format, so the partial surrogate pair is encoded into the BSON document but is not readable by the library. 

I've made [NODE-3175](https://jira.mongodb.org/browse/NODE-3175) to track this issue on our JIRA.

In terms of workarounds in the meantime: if the replacement character isn't an issue then continuing to use `js-bson` is the best solution. Otherwise adding additional logic to the string splitting might be necessary to ensure the strings passed in to the `bson-ext` library are complete glyphs.

**Comment by bajanam** [comment]
his issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket. Thanks!
